### ISSUE TITLE
什么时候可以更新一下LLamaSharp的依赖呢？

### ISSUE THREAD

**Issue by createworld123** [sangyuxiaowu/LLamaWorker#22]
现在好像不支持运行llama3.1模型

**Comment by sangyuxiaowu** [comment]
我测试的时候好像是支持，用的模型下载链接是中文的llama3.1配置文件里有下载链接。
另外也可以自行下载llama.cpp的最新的发行版替换对应的dll库的。
本来是更新了LLamaSharp的，感觉有问题，回退了，然后换到dev分支了
